name: CHSH-Game Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-cov pytest-timeout socketio-client-nexus
    
    - name: Run unit tests
      run: |
        pytest tests/unit/ -v
    
    - name: Run integration tests
      run: |
        pytest tests/integration/ -v
    
    - name: Run browser refresh tests
      run: |
        pytest tests/browser_refresh/ -v
    
    - name: Run connection stability tests
      run: |
        pytest tests/connection/ -v
    
    - name: Run stress tests (small scale)
      run: |
        pytest tests/stress/test_stress.py::test_many_concurrent_teams tests/stress/test_stress.py::test_rapid_answer_submissions tests/stress/test_stress.py::test_concurrent_game_actions -v
    
    - name: Generate coverage report
      run: |
        pytest --cov=src/ --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
