version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "8080:8080"
    command: gunicorn wsgi:app --worker-class eventlet --bind 127.0.0.0:8080
    environment:
      - FLASK_ENV=testing
  
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - app
    environment:
      - SERVER_URL=http://app:8080
      - FLASK_ENV=testing
    command: pytest tests/ -v
