version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "5000:5000"
    command: gunicorn wsgi:app --worker-class eventlet --bind 0.0.0.0:5000
    environment:
      - FLASK_ENV=testing
  
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - app
    environment:
      - SERVER_URL=http://app:5000
      - FLASK_ENV=testing
    command: pytest tests/ -v
