name: Python Tests

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*.*.*'  # Trigger on version tags like v1.2.3
  pull_request:
    branches: [ '**' ]

# Setting default permissions to read-only
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/load_test/load_test_requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r load_test/load_test_requirements.txt
    
    - name: Test with pytest and generate coverage report
      run: |
        pytest --cov=src --cov-branch --cov-report=xml tests/
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        
    - name: Run mypy type checking
      continue-on-error: true
      run: |
        echo "Running mypy type checking..."
        mypy src || echo "mypy found type issues (non-blocking)"
        
    - name: Run pyright type checking
      continue-on-error: true
      run: |
        echo "Running pyright type checking..."
        pyright || echo "pyright found type issues (non-blocking)"